site_name: MetaVision+ Documentation
site_author: Safety&Care AI 개발팀
site_description: Vision AI가 적용된 서비스의 데이터 관리 커버리지 및 활용성을 높이고, CVPaaS Cloud 서비스에서의 확장성 있고 비용 효율적인 AI Ops 서비스의 기반을 제공하여, Golden Data Discovery & AI 모델 개선 Cycle을 완성하기 위한 플랫폼
site_url: https://github.com/mnms/metavision-documents

copyright: All right reserved, <a href='#'>Safety&Care AI 개발팀</a>

nav:
- Introduction:
  - Overview: index.md
  - Register & Sign in: login.md
  - Create project: project.md

- Storage & Database:
  - Data Lake: data_lake.md
  - Data Warehouse: data_warehouse.md

- Data Agent:
  - Dashboard: dashboard.md
  - ML Workflow & Event: workflow_event.md

plugins:
- search

markdown_extensions:
- meta
- toc:
    permalink: true
    baselevel: 1
- admonition
- footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 1.0
