site_name: MetaVision Docs
site_author: Safety&Care AI 개발팀
site_description: Vision AI가 적용된 서비스의 데이터 관리 커버리지 및 활용성을 높이고, CVPaaS Cloud 서비스에서의 확장성 있고 비용 효율적인 AI Ops 서비스의 기반을 제공하여, Golden Data Discovery & AI 모델 개선 Cycle을 완성하기 위한 플랫폼
site_url: https://github.com/mnms/metavision-documents

copyright: All right reserved, <a href='#'>Safety&Care AI 개발팀</a>

nav:
- Introduction:
  - Overview: index.md
  - Register & Sign in: signin.md

- Storage & Database:
  - Projects: project.md
  - Datasets: datasets.md
  - Files: files.md

- Data Agent:
  - Developmental Disorder:
    - Introduction: intro_developmental_disorder.md
    - Group Monitoring: group_monitoring.md
    - Golden-Data Events: golden_data_events.md
    - AI Device Status: ai_device_status.md

- Search:
  - Semantic Search:
    - System Architecture: semantic_search_archi.md
    - UI Scenario: semantic_search.md
  - Advanced Search:
    - Event Search: event_search.md
    - Object Search: object_search.md
    - Similar Search: similar_search.md


plugins:
- search

markdown_extensions:
- meta
- toc:
    permalink: true
    baselevel: 1
- admonition
- footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 1.0
